sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  environment: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-734795248990"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "aws_access_key"
  secret_access_key: "aws_secret_key"
